apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: run-nvidia-smi-
spec:
  entrypoint: run-nvidia-smi
  templates:
  - name: run-nvidia-smi
    container:
      image: nvidia/cuda:12.1.1-runtime-ubuntu22.04
      command: [sh, -c]
      args:
      - |
        nvidia-smi
        nvidia-smi -L
    resources:
      limits:
        nvidia.com/gpu: "1"
